### ISSUE TITLE
Create interfaces

### ISSUE THREAD

**Issue by esodan** [grindhold/libgtkflow#11]
In order to provide powerful, very flexible implementations of your library, may be is useful to create interfaces for:

Dock, Source and Sink

I mean, your actual implementation should be re-named and implent the above interfaces.

With this we can construct two libraries:

* Node aware library called GFlow, no GUI tied, to create different implementation of its interfaces by third party, but with a set of default implementations.

* Gtk+ aware library called GtkFlow, making use of Gtk to "draw" GFlow.Node, GFlow.Source and GFlow.Sink objects

This is the way libgda [1] does.

With this logical separation, we can create Unit Tests to waranty GFlow works flowesly, maybe adding different implementations of GFlow.Node (for example) to make sure its API could cover any case, expected application.

GFlow, could make programing of complex processes and packaged in GFlow.Source, Node and Sink, representation to be reused by other libraries compatible with its sources and outputs.

GtkFlow, could use GFlow objects from any implementation, not just the ones in GFlow, to draw in screen and provide a GUI for complex processes' input/output interconections, as you made today. In the future, a plugin system could be added in order to "register" new GFlow.Node implementation from other libraries to use in your GUI.

What do you think?

[1] http://git.gnome.org/browse/libgda

**Comment by grindhold** [comment]
From a technical point of view this totally makes sense. Having small granular libraries surely enhances testability and should be preferred over huge monolithic blocks of binary.
Before we proceed doing such a thing, how would you like the API to look like?

(When i design a library the first thing i think of is the API towards the programmer. The question is "How would a thing look like that i'd like to use?")

Would you hide the generation of GFlow.Dock objects behind the methods of the GtkFlow implementation? Or would you do an approach like Gtk.TreeView where you define your data in a Gtk.TreeStore and then pass it on to the Gtk.TreeView to render? In our case this would be Creating GFlow.Docks and then passing them to GtkFlow.Nodes to render them.

**Comment by esodan** [comment]
El may 22, 2015 11:59 AM, "grindhold" <notifications@github.com> escribió:
>
> From a technical point of view this totally makes sense. Having small
granular libraries surely enhances testability and should be preferred over
huge monolithic blocks of binary.
> Before we proceed doing such a thing, how would you like the API to look
like?
>
> (When i design a library the first thing i think of is the API towards
the programmer. The question is "How would a thing look like that i'd like
to use?")
>
I'm still studying your code, but defining an interface from your classes'
methods is easy. For your classes API point of  view there is no change,
they'll remain as is today but implementing an interface.

I'll try to get interfaces proposal, but may you know better your code and
knows what parts is not GUI specific.

> Would you hide the generation of GFlow.Dock objects behind the methods of
the GtkFlow implementation? Or would you do an approach like Gtk.TreeView
where you define your data in a Gtk.TreeStore and then pass it on to the
Gtk.TreeView to render? In our case this would be Creating GFlow.Docks and
then passing them to GtkFlow.Nodes to render them.
>

The last is the way, I think. Making GtkFlow handle any object implementing
GFlow. Dock interface to render it is the best.

Then GFlow.Dock should provide all necessary API to help GtkFlow on
rendering.

We can add interfaces and add API step by step, ensuring not break any
thing. Or design an API then port your classes to it, as you prefer.

Just think GFlow is a general porpoise library to handle processes
interconnection pipe. And GtkFlow should render some kind of GFlow objects
and open to create new ones.

**Comment by grindhold** [comment]
I created an interface INode. I am going to write custom nodes on application level with it on my next project. If this does not suffice for convenient usage, i will consider creating more interfaces

**Comment by esodan** [comment]
In Vala, I think, they don't use prefix "I".

I think this interfaces should represent an Object of type "Node" then this
interface should be called "Node".

If this interface use other Objects to be implemented in diferent ways,
they should be interfaces too. This could apply to inputs and outputs,
because they could be not just values but signalds from/to other processes,
maybe for this first iteration just GValue values are Ok, but let any other
already existing objects to implement Node's inputs and outputs.

Sorry I haven't time to work here.
