### ISSUE TITLE
serialization.

### ISSUE THREAD

**Issue by grindhold** [grindhold/libgtkflow#17]
We should somehow make GtkFlow.NodeView serializable.

Imagine the following: A user opens a program that allows him to freely edit a NodeView. Now he shuts down the program and opens it at a later time. Now he wants to view the Nodes as he left them. We should somehow be able to read the content of a NodeView from a file and then restore a new NodeView with that data.

This would imply the following: The file format must be aware of Node types in order to call the right constructor. This must work with whatever Node the User decided to derive from GtkFlow.Node.
I don't have any clue whether this is even possible in Vala

The other option would be to leave this to the application level.
The application itself knows best what data it uses and how to store it most effectively. The only thing we must provide with this option is a possibility to read the allocations of nodes from the outside and let them be set programmatically from the outside.
I think, that this is the most viable option.
Let's discuss it first. Any other ideas?

**Comment by esodan** [comment]
GXml is a Vala library providing Serialization to XML to any object implementing Serializable interface.

It provides a default implementation, some kind C# serialization uses, where any object represent an XML node and its properties as XML tag's properties.

By implementing This in GtkFlow you'll have serialize/deserialize infrastructure to XML.

**Comment by grindhold** [comment]
So then the developer using GtkFlow can implement Serializable in his own object. Because he knows the special features of the Nodes he creates. On library level we can't decide that. By leaving it to the developer we also do not force him to use XML. I know loads of people who prefer JSON over XML. And there are still more serialization formats out there e.g. YAML and TOML.
