### ISSUE TITLE
Fix segfault

### ISSUE THREAD

**Issue by grindhold** [grindhold/libgtkflow#19]
Steps to reproduce with advanced_calculator.py:

  * Add 2 NumberNodes
  * Add 2 OperationNodes
  * Add 1 PrintNode
  * Connect one numbernode with input A of the first OperationNode
  * Connect the other numbernode with input B of the second OperationNode
  * Connect the output of the second OperationNode with input B of the first OperationNode
  * Connect the output of the first OperationNode with the PrintNode
  * Connect the output of the second OperationNode with the PrintNode
  * Connect the output of the first OperationNode with the PrintNode again
  * program segfaults.

**Comment by noice2** [comment]
ICQ

**Comment by grindhold** [comment]
@noice2 what do you mean by that?

**Comment by noice2** [comment]
I mean that I need you on your ICQ.

Or have a look in your gmx mailbox.

2015-05-29 16:42 GMT+02:00, grindhold <notifications@github.com>:
