### ISSUE TITLE
gflow integration

### ISSUE THREAD

**Issue by grindhold** [grindhold/libgtkflow#24]
Hiho, @esodan. I have now set up a branch <s>gflow_integration</s> gflow_wiring in order to wire gtkflow to gflow.

I have no more compiler errors on gtkflow's side, but on gflow's side i have. The GFlow.Dock defines an abstract nullable property Node which is being implemented by GFlow.SimpleSource and GFlow.SimpleSink. Both interfaces GFlow.Sink and GFlow.Source inherit from GFlow.Dock. Yet the compiler complains that there are no get_node() and set_node() methods in GFlow.Sink and GFlow.Source. 

When i try to add an explicit override to the node-properties in GFlow.SimpleSink and GFlow.SimpleSource, the compiler tells me, that no suitable property could be found to override.
I don't get it. Is there something wrong with the inheritance code? Could you have a look?

I will now continue with creating the missing signals and further code-wiring between GtkFlow and GFlow.

<s> Update: there went something wrong with branching. I will re-setup the branch. This may take a few minutes. </s>

Update: Same goes for the sinks property and the supposedly existing method get_sinks() of GFlow.Source.

**Comment by esodan** [comment]
I've managed to fix most issues in my repository and added infrastucture
for Unit Tests. ASAP I'll send a merge request.

**Comment by grindhold** [comment]
wonderful. i am eager to see why this abstract property inheritance didn't work.

**Comment by esodan** [comment]
This is because it a property not a method. You should use:

On get:
 s.node

On set:
 s.node = 

After this modifications on your code pass GFlow build. I can't warranty this code will work property, because no all Unit Test are done jet.

I've found lot of errors on GtkFlow now because you try to decent from two object, if removed the GFlow.Node for GtkFlow.Node, I get lot of errors because most methods aren't defined. As explained in other merge request, you should add properties to hold GFlow objects.

**Comment by esodan** [comment]
I have send you a merge request in order to see my changes, but I don't recommend to continue in that branch unless all classes and interfaces in GFlow are fixed and working properly, using Unit Test as the ones I've added.

**Comment by grindhold** [comment]
i thought that a property implies the creation of get- and set-methods or is this only true for the use of properties through gobject-introspection?

**Comment by esodan** [comment]
In vala a property is declared as:

public string name { get; set; }

Then when it is translated to C through gflow.h, for example, you will have name_get () and a name_set () methods, they will be available to gobject-introspection to be used by bindings, but at the same time they are GObject properties, then you can use g_object_get_property() on C to access them, add some semantics to its description and get signals notifications on change.

If you declare a function name_set () it is a method not a property and can't be used as above.

**Comment by grindhold** [comment]
thx for the explanation, say would you care for a mumble-session to discuss how we implement stuff a bit quicker? do you have a headset? we can then post a transcript of what we plan to do and how we plan to do it in a issue here. I'd send you the credentials to a mumble server via email.

**Comment by esodan** [comment]
I don't know about mumble, but may you can help me.

We can arrange a meeting, of course.

2015-06-10 12:09 GMT-05:00 grindhold <notifications@github.com>:

> thx for the explanation, say would you care for a mumble-session to
> discuss how we implement stuff a bit quicker? do you have a headset? we can
> then post a transcript of what we plan to do and how we plan to do it in a
> issue here. I'd send you the credentials to a mumble server via email.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grindhold/libgtkflow/issues/24#issuecomment-110837800>
> .
>



-- 
Trabajar, la mejor arma para tu superación
"de grano en grano, se hace la arena" (R) (en trámite, pero para los
cuates: LIBRE)

**Comment by grindhold** [comment]
i've sent you an email with all relevant instructions. if something's missing, don't hesitate to ask

**Comment by grindhold** [comment]
meeting was done, rough plan was written to wiki.
