### ISSUE TITLE
GFlow.Sink

### ISSUE THREAD

**Issue by esodan** [grindhold/libgtkflow#27]
For GFlow.Sink interface I'm planning to remove virtual methods to set a source, to leave that to implementators, like SimpleNode actually.

This means to remove Error thrown, but should be documented that implementations should send a "connected" signal when connected to a new source.

Do you agree?

**Comment by grindhold** [comment]
i agree

**Comment by esodan** [comment]
I've found that GFlow.Sink and GFlow.Source interfaces have more methods they really need.

I'm simplifying them to relay only on signals from Dock to know when they are connected, disconected or updated, and leave implementators to decide how they want to hold their information.

This makes SimpleSink and SimpleSource grow in methods, some of them hidden to be used just when connect/disconnect from Dock.

If you agree, I'll continue fixing my compiler errors and send a merge request.

**Comment by grindhold** [comment]
i agree. keeping interfaces simple makes it easier for programmers to use them. please proceed.

**Comment by esodan** [comment]
I'm ready to merge. Please review next merge request

**Comment by grindhold** [comment]
i'd like to, but there still is no new merge-request. btw: did you read my offer in the other ticket?

**Comment by grindhold** [comment]
i think this is done
