### ISSUE TITLE
gflow: further implementation

### ISSUE THREAD

**Issue by grindhold** [grindhold/libgtkflow#30]
ohai @esodan 

little statusreport upfront to this issue:

Over the last day, i rewrote GtkFlow to work together with GFlow. Afterwards i got all three current example-scripts to work against the new API. Some major things have changed:
  1. GtkFlow Now exposes the interfaces NodeRenderer and DockRenderer. These can be used by users to render customized GtkFlow.Nodes from GFlow.Nodes. The Classes GtkFlow.Sink, GtkFlow.Source and GtkFlow.Dock have been dropped. GtkFlow.Node is now private to GtkFlow.
  2. show_types is now an attribute of GtkFlow.NodeView, not of GtkFlow.Node
  3. to add nodes to a GtkFlow.NodeView, use GtkFlow.NodeView.add_node(GFlow.Node n) or GtkFlow.NodeView.add_with_child(GFlow.Node n, Gtk.Widget child)
  4. I changed the signals of GFlow.Node that express that Docks have changed in this Node to four separate signal, that supply the Dock in concern.

Suggestions:
  - I am not in favor of the "updated" signal when it comes to docks and their values, as throughout the rest of Gtk, when using a Widget i never used before, I will intuitively look for a "changed"-signal for that before anything else. Let's keep the naming.
  - For Docks themselves, the "changed" signal for "something changed in sinks or sources" of a dock is obsolete in my opinion, because we have "connected" and "disconnected".

**Comment by esodan** [comment]
Geat news!

All is taking a very well designed API.

For your comments. Ok keep "changed" signal and use it on any Dock. I was
using "updated" one for Source objects but use "changed" for any data
source change is Ok.

**Comment by grindhold** [comment]
everything discussed here has been done, i think.
