### ISSUE TITLE
Don't know how to Setup GtkFlow.NodeView

### ISSUE THREAD

**Issue by esodan** [grindhold/libgtkflow#34]
I'm trying to create a test application, running it on Unit Tests make check. But I don't know how to initiate a GtkFlow.NodeView. I'm using the following code:

var app = new GuiNodeTest (); // This is a Gtk.Window App with a window property to add Gtk.NodeView
 var nview = new GtkFlow.NodeView ();
 var node = new GFlow.SimpleNode ();

I've tried this:

nview.add_node (node); 

But fails on nodeview.vala:161 with following message:

libgtkflow-WARNING **: nodeview.vala:161: You can only add GFlow.Nodes to GtkFlow.NodeViews. Please use NodeView.add_node or NodeView.add_node_with_child

Then tried this:
 var wnode = new GtkFlow.Node (node);
 nview.add (node);

libgtkflow/node.vala exists, but is not added to library, then it is not defined. What do I need to do to make my app test create a NodeView widget and add it to my Gtk.Window?

**Comment by grindhold** [comment]
you did everything right. at the first time. using add_node is the valid way. unfortunately add_node internally calls add. and this leads to prints the warning anyway. Maybe we should remove the warning and tell people to use add_node and remove_node in the documentation and in tutorials. The warning is a bit misleading.

**Comment by esodan** [comment]
Ok. But when on Unit Test any warning is considered an error then it stop
the test and quit with error.

My last commit set up almost all just require to fix this in order to start
testing GtkFlow.

**Comment by grindhold** [comment]
i removed the warnings. gtkflow-test now passes (or at least it shows "PASSED").

**Comment by esodan** [comment]
Could you uncomment the line:

nview.add_node (node)

and test? This was the source of my first problem.

Consider that GFlow.Simple* implementations should not add more API than
its interfaces in order to validate interfaces API.

I hope I'll take some time to review tests to focus on interfaces API.
