### ISSUE TITLE
build debian package

### ISSUE THREAD

**Issue by grindhold** [grindhold/libgtkflow#36]

**Comment by grindhold** [comment]
@esodan do you have experience building packages based on the autotools system you have set up? i get confused with the naming. especially how to get everything in there (library version , api version, abi version, debian-package version) e.t.c.

**Comment by esodan** [comment]
Long time ago I've created a Debian package, I don't remember well how, but
once we have a release we will find a good packager who will help on upload
as an Official Debian package.

Once we finish all Unit Test pass to test most basic functionality, and
make check too, we will have a tarball suitable to create a Debian package
from.

**Comment by grindhold** [comment]
done, see https://github.com/grindhold/libgtkflow_packaging
