### ISSUE TITLE
Sinks should allow multiple connected sources

### ISSUE THREAD

**Issue by benwaffle** [grindhold/libgtkflow#52]
Useful for audio

**Comment by grindhold** [comment]
i think i will create a new property for docks that determines
how many connections can be made to the dock.

**Comment by benwaffle** [comment]
sounds useful

**Comment by dankasak** [comment]
I would also find this very useful

**Comment by grindhold** [comment]
As of today, programmers can use SimpleSink.set_max_sources(int number) to allow connections of multiple Sources to a Sink.
Please be aware that this introduced significant changes to the API.  SimpleSink.get_value now expects a parameter that specifies the index of the source to read.
Also see the newly created example in `examples/multisink.py` to understand how to use multiple sources on a sink.

Have fun developing with it!
