### ISSUE TITLE
Compilation issue: GFlow-0.2.gir: Error on line 1 char 1: Document was empty or contained only whitespace

### ISSUE THREAD

**Issue by dankasak** [grindhold/libgtkflow#59]
I'm trying to build from git. I had to comment out some valadoc stuff, because valadoc doesn't appear to be packaged by my distro ( Gentoo ). The build fails:

dkasak@sabayon-latitude ~/src/libgtkflow/build $ meson ..
The Meson build system
Version: 0.33.0
Source dir: /home/dkasak/src/libgtkflow
Build dir: /home/dkasak/src/libgtkflow/build
Build type: native build
Build machine cpu family: x86_64
Build machine cpu: x86_64
Project name: gtkflow
Native vala compiler: valac (unknown 0.32.1)
Native c compiler: cc (gcc 4.9.3)
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency glib-2.0 found: YES 2.50.2
Native dependency gobject-2.0 found: YES 2.50.2
Native dependency gtk+-3.0 found: YES 3.22.3
Library m found: YES
Program g-ir-compiler found: YES (/usr/bin/g-ir-compiler)
Warning: Unknown keyword argument(s) in target gflow-0.2: vala_gir.
Warning: Unknown keyword argument(s) in target gtkflow-0.2: vala_gir.
Build targets in project: 5
dkasak@sabayon-latitude ~/src/libgtkflow/build $ ninja
[10/29] Compiling c object 'libgflow/gflow-0.2@sha/libgflow_gflow-0.2@sha_gflow-simple-node.c.o'
/home/dkasak/src/libgtkflow/libgflow/gflow-simple-node.vala: In function ‘gflow_simple_node_real_is_recursive_forward’:
/home/dkasak/src/libgtkflow/libgflow/gflow-simple-node.vala:152:17: warning: comparison of distinct pointer types lacks a cast
             if (!initial && this == from)
                 ^
/home/dkasak/src/libgtkflow/libgflow/gflow-simple-node.vala: In function ‘gflow_simple_node_real_is_recursive_backward’:
/home/dkasak/src/libgtkflow/libgflow/gflow-simple-node.vala:168:17: warning: comparison of distinct pointer types lacks a cast
             if (!initial && this == from)
                 ^
[13/29] 'Generating gflow-typelib with a custom command.'
FAILED: '/usr/bin/g-ir-compiler' '--output' 'libgflow/GFlow-0.2.typelib' '/home/dkasak/src/libgtkflow/build/libgflow/GFlow-0.2.gir' '--shared-library' '/usr/local/lib/x86_64-linux-gnu/libgflow-0.2.so'
error parsing file /home/dkasak/src/libgtkflow/build/libgflow/GFlow-0.2.gir: Error on line 1 char 1: Document was empty or contained only whitespace
[13/29] Compiling Vala source ../libgtkflow/dock_renderer.vala ../libgtkflow/node_renderer.vala ../libgtkflow/node.vala ../libgtkflow/nodeview.vala.
ninja: build stopped: subcommand failed.
dkasak@sabayon-latitude ~/src/libgtkflow/build

**Comment by grindhold** [comment]
in 4d5d37a i added a minimum meson version to be checked.
if you encounter any lower meson-versions that are able to
build the project correctly, feel free to adjust the value
in ```meson.build```

**Comment by dankasak** [comment]
Yikes! And I thought _**I**_ was bleeding-edge.
