### ISSUE TITLE
API for getting / setting position of nodes

### ISSUE THREAD

**Issue by dankasak** [grindhold/libgtkflow#61]
Is there an API for getting / setting the position of nodes? It would be great to be able to implement loading and saving in my app, so items can be restored to where a user arranged them.

**Comment by grindhold** [comment]
there is.
NodeView.set_node_position()
NodeView.get_node_position()
I already did this in my prototype for pinmagic:
https://github.com/grindhold/pinmagic_prototype/blob/561723e0aaae8eaca31018d760434292ba9a1df6/pinmagik/application.py#L183
The whole serializer/deserializer classes may be of interest to you :)
