### ISSUE TITLE
autoupdate size of nodes if node content expands

### ISSUE THREAD

**Issue by grindhold** [grindhold/libgtkflow#62]
@schlagenhauf wrote https://github.com/schlagenhauf/indprog in which nodes contain an expander. if the node is small and the content is being expanded, the node contents will render outside the node until one moves the node or manually resizes it.
the nodeview should listen to size-changes inside the node-children and cause redraw on receiving such an event.

**Comment by schlagenhauf** [comment]
Wow, that's some proactive support! Can confirm that this is an issue and a fix would be greatly appreciated. Nice job with the library btw.

**Comment by grindhold** [comment]
here you go :)
