### ISSUE TITLE
Gee version

### ISSUE THREAD

**Issue by esodan** [grindhold/libgtkflow#7]
Are you planning to use old Gee 0.6, as gee-1.0, or just the more stable series of Gee 0.16 and above?

If the last, I'll make to require just Gee 0.16 (gee-0.8).

**Comment by grindhold** [comment]
i like to use the version of gee that can be found as libgee-0.8-2 in debian stretch. according to apt, this maps to the source version 0.16.1-1 of libgee

**Comment by esodan** [comment]
Ok.

My recent pull request, I considered to use just recent version of Gee, then it just check for gee-0.8, this package (gee-0.8), consider all new versions of Gee and avoid to use old Gee 0.6 version.

**Comment by grindhold** [comment]
wonderful
