### ISSUE TITLE
Hearder files intallation

### ISSUE THREAD

**Issue by esodan** [grindhold/libgtkflow#8]
I'm planning to install your header files in a location libgtkflow/gtkflow.h, but with a prefix depending on stabel version.

This is very common for parallel installations, you can have a 0.2 API in a directory libgtkflow-0.2/libgtkflow and a 0.4 API (may be incompatible with the last) at libgtkflow-0.4/libgtkflow. Then we can use gtkflow-0.2.pc for others to use 0.2 API and gktflow-0.4.pc for 0.4 API.

This is impartant in order to avoid problems like the one Gee falls in the time.

But for this I need you to rename your src directory to libgtkflow. You should rename your file gtkflow.pc to gktflow-0.2.pc, for the next stable API.

Please confirm in order to continue Autotools setup.

This is the same I'm using on GXml.

**Comment by esodan** [comment]
Please consider that, for parallel installation libgtkflow.so should be renamed to libgtkflow-0.2.so, for the next stable version.

**Comment by grindhold** [comment]
parallel installation makes sense. feel free to do the neccessary renames in your repo, i'll merge them in.

a question about renaming libgtkflow.so. shouldn't the name for the shared library file be decided in the buildsystem? or will this require manual renaming?

**Comment by esodan** [comment]
You should rename manually with each version you are maintaining.

When you install a 0.2 version package, you'll get libgtkflow-0.2.so in {prefix}/lib, but you need a libgtkflow-0.4.so version, in the same directory, to get a 0.2 version package installed and your user could link agains the one they need.

**Comment by grindhold** [comment]
ok
